groups:
  - name: node-exporter-alerts
    rules:
      # CPU load is > 80%
      - alert: HostHighCpuLoad
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Disk is almost full (< 10% left)
      # Please add ignored mountpoints in node_exporter parameters like
      # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
      # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
      - alert: HostOutOfDiskSpace
        expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      #Node RAM memory is filling up (< 10% left)
      - alert: HostOutOfMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory (instance {{ $labels.instance }})
          description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

# groups:
#   - name: node-exporter-alerts
#     interval: 30s  # Evaluate every 30s
#     rules:
#       # High CPU Usage
#       - alert: HostHighCPUUsage
#         expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 90
#         for: 2m
#         labels:
#           severity: critical
#         annotations:
#           summary: "High CPU Usage detected on {{ $labels.instance }}"
#           description: "The CPU usage is above 90% for more than 2 minutes on {{ $labels.instance }}."

#       # Out of Disk Space
#       - alert: HostOutOfDiskSpace
#         expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
#         for: 5m
#         labels:
#           severity: warning
#         annotations:
#           summary: "Low Disk Space on {{ $labels.instance }}"
#           description: "The disk space is below 10% on {{ $labels.instance }} for more than 5 minutes."

#       #Out of Memory
#       - alert: HostOutOfMemory
#         expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 5
#         for: 2m
#         labels:
#           severity: critical
#         annotations:
#           summary: "Low Memory on {{ $labels.instance }}"
#           description: "Available memory is below 5% for more than 2 minutes on {{ $labels.instance }}."
