groups:
  - name: nginx_alerts
    rules:
      - alert: NginxProxyDown
        expr: nginx_up{addr="http://proxy:8080/stub_status"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx Proxy instance is down"
          description: "Nginx Proxy instance has been down for more than 1 minute."
