---
  - name: Stop and remove docker containers
    hosts: ec2_hosts
    become: yes
    tasks:
      - name: print app_dest_path
        debug:
          msg : |
            app_dest_path: {{ app_dest_path }}

      - name: Check existence of project folder
        ansible.builtin.stat:
          path: "{{ app_dest_path }}"
        register: p

      - name: print if is_dir
        debug:
          msg: "{{ app_dest_path }} exists and is a directory"
        when: p.stat.isdir is defined and p.stat.isdir
        # when: p.stat.exists and p.stat.isdir

      - name: docker Stop
        community.docker.docker_compose_v2:
          project_src: "{{ app_dest_path }}"
          state: absent
        when: p.stat.isdir is defined and p.stat.isdir
        # when: p.stat.exists and p.stat.isdir

