#
# Docker System Prune Playbook
#
# Usage:
#   ansible-playbook playbooks/prune_images.yml -i <your_inventory>
#
#   This playbook will prune (clean up) all stopped containers, unused networks, dangling images, unused volumes, and build cache
#   on the target Docker host. It is equivalent to running `docker system prune` on the host.
#   Running containers and images in use will NOT be removed.
#

---
- name: Prune Docker resources on target hosts
  hosts: hetzner_instance
  become: yes

  tasks:

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true

    # - name: Prune containers older than 24h
    #   community.docker.docker_prune:
    #     containers: true
    #     containers_filters:
    #       # only consider containers created more than 24 hours ago
    #       until: 24h

    # - name: Prune containers with labels
    #   community.docker.docker_prune:
    #     containers: true
    #     containers_filters:
    #       # Prune containers whose "foo" label has value "bar", and
    #       # whose "bam" label has value "baz". If you only want to
    #       # compare one label, you can provide it as a string instead
    #       # of a list with one element.
    #       label:
    #         - foo=bar
    #         - bam=baz
    #       # Prune containers whose label "bar" does *not* have value
    #       # "baz". If you want to avoid more than one label, you can
    #       # provide a list of multiple label-value pairs.
    #       "label!": bar=baz

    # - name: Prune everything (including non-dangling images)
    #   community.docker.docker_prune:
    #     containers: true
    #     images: true
    #     images_filters:
    #       dangling: false
    #     networks: true
    #     volumes: true
    #     builder_cache: true